# mandatory parameters
metadata_dir: /home/creyna/Vogl-lab_Projects_git/HCC_MUW_analysis/Data/Metadata
data_dir: /home/creyna/Vogl-lab_Projects_git/HCC_MUW_analysis/Data
lib_meta_data: aligent_twist_with_important_info_excludeSARS.pkl
project: HCC_MUW
group_tests:
#  - non Cirrhosis
#  - Cirrhosis
  - Controls
  - HCC

###
# filter metadata (optional if not all samples are needed)
filters_metadata:
#  Centre: Hamburg
  group_test:
    - Controls
    - HCC
# Optional parameters with defaults
meta_typefile: excel
col_sample_name: SampleName
col_target: group_test
col_predict: class1_proba
random_state: 420

# Features and thresholds
extra_features_to_include:
  - Sex
  - Age
data_types:
  - exist
#  - fold
#  - p_val
prevalence_thresholds_min:
#  - 2.0
  - 5.0
  - 10.0
  - 20.0
  - 50.0
prevalence_thresholds_max:
  - 95.0

# Options for data processing
# Either all peptides and/or extra features
with_oligos_options:
  - true
  - false
with_additional_features_options:  
#if you want to include sex and age
  - true 
  - false
with_run_plates_options:
  - false
# - true if you want to inclide the plates as extra feature
filter_by_entropy:
  - false
#  - true
#entropy_threshold: 0.4
filter_by_correlation:
  - false

# Subgroup settings
subgroups_to_name:
  all: Complete library
  bloodtests: Blood tests
  is_ALIGENT: Aligent library
  is_TWIST: Twist library
  is_CORONA: Corona library
  is_PNP: "Metagenomics\nantigens"
  is_auto: Human Autoantigens
  is_patho: Pathogenic strains
  is_probio: Probiotic strains
  is_IgA: "Antibody-coated\nstrains"
  is_MPA: "Microbiota\nstrains"
  is_bac_flagella: Flagellins
  is_infect: "Infectious\npathogens"
  is_EBV: "Epstein-Barr\nVirus"
  is_toxin: Toxin
  is_phage: Phages
  is_allergens: Allergens
  is_influenza: Influenza
  is_EM: "Microbiota\ngenes"
  signalp6_slow: Secreted proteins
  "is_topgraph_new_&_old": Membrane proteins
  diamond_mmseqs_intersec_toxin: Predicted toxins
  is_IEDB_or_cntrl: IEDB/controls
  is_pos_cntrl: Positive control
  is_neg_cntrl: Negative control
  is_rand_cntrl: Random control
subgroups_order:
  - Complete library
  - Aligent library
  - Twist library  # 'Corona library',
  - "Metagenomics\nantigens"
  - Human Autoantigens
  - Pathogenic strains
  - Probiotic strains
  - "Antibody-coated\nstrains"
  - "Microbiota\nstrains"
  - Flagellins
  - "Infectious\npathogens"
  - "Epstein-Barr\nVirus"
  - Toxin
  - Phages
  - Allergens
  - Influenza
  - "Microbiota\ngenes"
  - Secreted proteins
  - Membrane proteins
  - Predicted toxins
  - IEDB/controls
  - Positive control
  - Negative control
  - Random control
subgroups_to_include:
  - all
  - is_ALIGENT
  - is_TWIST
  - is_PNP
  - is_auto
  - is_patho
  - is_probio
  - is_IgA
  - is_MPA
  - is_bac_flagella
  - is_infect
  - is_EBV
  - is_toxin
  - is_phage
  - is_allergens
  - is_influenza
  - is_EM
  - signalp6_slow
  - is_topgraph_new_&_old
  - diamond_mmseqs_intersec_toxin
  - is_IEDB_or_cntrl
  - is_pos_cntrl
  - is_neg_cntrl
  - is_rand_cntrl

# Estimators
estimators_info:
  XGBClassifier:
    estimator_class: 'xgboost.XGBClassifier'
    estimator_kwargs:
      objective: 'binary:logistic'
      eval_metric: 'auc'
      random_state: 420
      nthread: 1
      n_jobs: -1
      n_estimators: 150
      learning_rate: 0.1
      max_depth: 6

# Parameter grid for hyperparameter tuning
param_grid:
  XGBClassifier:
    n_estimators: [50, 100, 200, 500, 1000]
    learning_rate: [0.01, 0.1, 0.3]
    max_depth: [4, 6, 8]
    subsample: [0.6, 0.8, 1.0]
    colsample_bytree: [0.6, 0.8, 1.0]
    reg_lambda: [1, 1.5, 2, 3]

# parameters for internal classes
transposed: true
imputed: false
fillna: false
libraries_prefixes:
  - agilent
  - corona2
  - twist
cv_method: kfold #loo
split_train_test: true #false
compute_feature_importance: true
return_train: true
return_test: true
external_set: false

tuning_parameters: true
train_size: 0.8
k: 10
tuning_n_iter: 30
tuning_k: 5
